import crypto from 'crypto';
import type { DB } from '../../../db/connection';
import { Errors } from '../../../core/errors';
import { isAccountVisibleForScope } from '../../../core/accountScope';
import { parseActualImport,resolveActualImport } from '../../io/excel';
import { loadSnapshotNodes } from '../../tree/snapshot';
import { adapterFor } from '../parser/fixed-finance-system';
import type { AccountMapping,OrgMapping } from '../mapping/matcher';
import { amountFor,matchAccounts,matchOrg } from '../mapping/matcher';
import { allocateFixedRatio } from '../mapping/allocator';
import type { ConvertedRow,FinanceProfileConfig,FinanceValidationReport,NormalizedFinanceRow,NormalizedProfitRow,ValidationIssue } from '../finance.types';
import { buildActualImportExcel } from './output-excel';
import { reconcile } from './reconciliation';

export interface ConvertInput{balance:Buffer;profit:Buffer;journal?:Buffer;year:number;snapshotDate:string;profile:{id:number;adapter_type:string;config_json:string};mappingVersion:{id:number;status:string;org_tree_snapshot_id:number;account_tree_snapshot_id:number};balanceSha256?:string;profitSha256?:string;journalSha256?:string;conversionBatchId?:number}
export interface ConversionResult{normalized:NormalizedFinanceRow[];profits:NormalizedProfitRow[];rows:ConvertedRow[];report:FinanceValidationReport;output?:Buffer}
const sha=(b:Buffer)=>crypto.createHash('sha256').update(b).digest('hex');
function descendants(nodes:{id:number;parent_id:number|null;code:string}[],roots:string[]):Set<number>{const out=new Set(nodes.filter(n=>roots.includes(n.code)).map(n=>n.id));let changed=true;while(changed){changed=false;for(const n of nodes)if(n.parent_id!=null&&out.has(n.parent_id)&&!out.has(n.id)){out.add(n.id);changed=true;}}return out;}

export async function convertFinanceActuals(db:DB,input:ConvertInput):Promise<ConversionResult>{
  if(input.mappingVersion.status!=='locked')throw Errors.validation('正式转换只能使用已锁定映射版本');const config=JSON.parse(input.profile.config_json||'{}') as FinanceProfileConfig;const adapter=adapterFor(input.profile.adapter_type);const context={year:input.year,snapshotDate:input.snapshotDate,config};
  const normalized=await adapter.parseBalance(input.balance,context),profits=await adapter.parseProfit(input.profit,context);const errors:ValidationIssue[]=[];const warnings:ValidationIssue[]=[];
  const prefixes=(config.sourceAccountIncludePrefixes??[]).map(String).filter(Boolean);const inSourceScope=(row:NormalizedFinanceRow)=>!prefixes.length||prefixes.some(prefix=>row.accountCode.startsWith(prefix));
  const scoped=normalized.filter(inSourceScope),excludedNonZero=normalized.filter(row=>!inSourceScope(row)&&(row.cumulativeDebitCents!==0||row.cumulativeCreditCents!==0));
  if(excludedNonZero.length)warnings.push({gate:'mapping',code:'SOURCE_ROWS_OUTSIDE_INCLUDED_SCOPE',message:`显式源科目范围外有 ${excludedNonZero.length} 个非零末级科目，已留痕且不参与预算转换`});
  let journalVerification;
  if(input.journal){if(!adapter.verifyJournal)throw Errors.validation('当前适配器不支持序时簿核验');journalVerification=await adapter.verifyJournal(input.journal,normalized,context);if(!journalVerification.passed)errors.push({gate:'journal',code:'JOURNAL_BALANCE_MISMATCH',message:`序时簿与余额表有 ${journalVerification.mismatchCount} 个科目不一致`});}
  else if(config.journalRequired)errors.push({gate:'journal',code:'JOURNAL_REQUIRED',message:'该数据源要求上传凭证序时簿进行逐分核验'});
  const orgRules=db.prepare('SELECT * FROM finance_org_mapping WHERE mapping_version_id=?').all(input.mappingVersion.id) as OrgMapping[];const accountRules=db.prepare('SELECT * FROM finance_account_mapping WHERE mapping_version_id=?').all(input.mappingVersion.id) as AccountMapping[];
  const orgNodes=loadSnapshotNodes(db,input.mappingVersion.org_tree_snapshot_id),accountNodes=loadSnapshotNodes(db,input.mappingVersion.account_tree_snapshot_id);const orgById=new Map(orgNodes.map(n=>[n.id,n])),accountById=new Map(accountNodes.map(n=>[n.id,n]));const values=new Map<string,ConvertedRow>();let sourceCents=0,allocatedCents=0;const sourceBreakdown=new Map<string,{source:number;allocated:number}>();const addBreakdown=(key:string,source:number,allocated:number)=>{const old=sourceBreakdown.get(key)??{source:0,allocated:0};sourceBreakdown.set(key,{source:old.source+source,allocated:old.allocated+allocated});};const nonZero=scoped.filter(r=>r.cumulativeDebitCents!==0||r.cumulativeCreditCents!==0);
  for(const row of nonZero){try{const orgRule=matchOrg(row,orgRules),rules=matchAccounts(row,accountRules),amount=amountFor(row,rules[0].amount_rule);const targets=rules.map(rule=>{const n=accountById.get(rule.target_account_id);if(!n||!['income','cost','expense'].includes(n.type??''))throw new Error('目标科目不是有效金额科目');return{rule,node:n};});const allocations=rules.length===1?[amount]:allocateFixedRatio(amount,targets.map(t=>({targetCode:t.node.code,weight:t.rule.allocation_weight})));const rowAllocated=allocations.reduce((s,v)=>s+v,0);sourceCents+=amount;addBreakdown(`account:${row.accountCode}`,amount,rowAllocated);addBreakdown(`org:${row.bookCode}|${row.orgCode}|${row.orgName}`,amount,rowAllocated);for(let i=0;i<targets.length;i++){const org=orgById.get(orgRule.target_org_id)!;const target=targets[i];const key=`${org.id}:${target.node.id}`;const previous=values.get(key);values.set(key,{year:input.year,snapshotDate:input.snapshotDate,orgId:org.id,orgCode:org.code,accountId:target.node.id,accountCode:target.node.code,accountType:target.node.type as ConvertedRow['accountType'],displayCents:(previous?.displayCents??0)+allocations[i]});allocatedCents+=allocations[i];addBreakdown(`category:${target.node.type}`,i===0?amount:0,allocations[i]);}}catch(err){errors.push({gate:'mapping',code:'ROW_MAPPING_FAILED',message:err instanceof Error?err.message:String(err),sourceSheet:row.sourceSheet,sourceRow:row.sourceRow});}}
  // 完整累计快照:在数据源拥有范围的有效叶子组合中显式补零；范围外永不输出。
  // 拥有范围编码必须都能在映射绑定快照中解析:锁定后树变更(根被删/改码)导致静默缩小时,
  // 补零范围会缺一块,该块上期残留实际数不会被显式零值清除。
  const ownedOrgCodeList=(config.ownedOrgCodes??[]).map(String),ownedAccCodeList=(config.ownedAccountCodes??[]).map(String);
  const unresolvedOrgs=ownedOrgCodeList.filter((c)=>!orgNodes.some((n)=>n.code===c)),unresolvedAccs=ownedAccCodeList.filter((c)=>!accountNodes.some((n)=>n.code===c));
  if(unresolvedOrgs.length||unresolvedAccs.length)errors.push({gate:'mapping',code:'OWNED_SCOPE_UNRESOLVABLE',message:`数据源拥有范围编码在映射绑定快照中不存在: ${[...unresolvedOrgs.map((c)=>`组织 ${c}`),...unresolvedAccs.map((c)=>`科目 ${c}`)].join(', ')}`});
  const ownedOrgIds=descendants(orgNodes,ownedOrgCodeList),ownedAccIds=descendants(accountNodes,ownedAccCodeList);const orgParents=new Set(orgNodes.map(n=>n.parent_id).filter((x):x is number=>x!=null)),accParents=new Set(accountNodes.map(n=>n.parent_id).filter((x):x is number=>x!=null));
  for(const row of values.values()){if(!ownedOrgIds.has(row.orgId)||!ownedAccIds.has(row.accountId))errors.push({gate:'mapping',code:'TARGET_OUTSIDE_OWNED_SCOPE',message:`映射目标 ${row.orgCode}/${row.accountCode} 超出数据源拥有范围`});if(!isAccountVisibleForScope(row.accountCode,new Set([row.orgCode])))errors.push({gate:'mapping',code:'TARGET_NOT_APPLICABLE',message:`科目 ${row.accountCode} 不适用于组织 ${row.orgCode}`});}
  if(!ownedOrgIds.size||!ownedAccIds.size)errors.push({gate:'output',code:'OWNED_SCOPE_REQUIRED',message:'数据源必须声明 ownedOrgCodes 和 ownedAccountCodes 完整拥有范围'});else for(const org of orgNodes.filter(n=>ownedOrgIds.has(n.id)&&!orgParents.has(n.id)&&n.status==='active'))for(const acc of accountNodes.filter(n=>ownedAccIds.has(n.id)&&!accParents.has(n.id)&&n.status==='active'&&n.type!=='quantity')){if(!isAccountVisibleForScope(acc.code,new Set([org.code])))continue;const key=`${org.id}:${acc.id}`;if(!values.has(key))values.set(key,{year:input.year,snapshotDate:input.snapshotDate,orgId:org.id,orgCode:org.code,accountId:acc.id,accountCode:acc.code,accountType:acc.type as ConvertedRow['accountType'],displayCents:0});}
  const rows=[...values.values()].sort((a,b)=>a.orgCode.localeCompare(b.orgCode)||a.accountCode.localeCompare(b.accountCode));const conservationPassed=sourceCents===allocatedCents;if(!conservationPassed)errors.push({gate:'conservation',code:'BATCH_NOT_CONSERVED',message:`批次金额不守恒:${sourceCents} != ${allocatedCents}`});const rec=reconcile(db,input.mappingVersion.id,profits,rows);errors.push(...rec.errors);
  const balanceSha256=input.balanceSha256??sha(input.balance),profitSha256=input.profitSha256??sha(input.profit),journalSha256=input.journal?(input.journalSha256??sha(input.journal)):undefined;let output:Buffer|undefined;let outputSha256:string|undefined;
  if(errors.length===0){output=await buildActualImportExcel(rows,{conversionBatchId:input.conversionBatchId,mappingVersionId:input.mappingVersion.id,balanceSha256,profitSha256});if(output.length>(config.maxOutputBytes??10*1024*1024)){errors.push({gate:'output',code:'OUTPUT_TOO_LARGE',message:'标准文件超过配置的字节上限'});output=undefined;}else{const parsed=await parseActualImport(output,db);resolveActualImport(db,parsed,false);outputSha256=sha(output);}}
  const breakdown=(prefix:string)=>Object.fromEntries([...sourceBreakdown.entries()].filter(([k])=>k.startsWith(prefix)).map(([k,v])=>[k.slice(prefix.length),{sourceCents:v.source,allocatedCents:v.allocated,differenceCents:v.allocated-v.source,passed:v.source===v.allocated}]));
  const report:FinanceValidationReport={passed:errors.length===0,counts:{sourceRows:normalized.length,nonZeroRows:nonZero.length,excludedNonZeroRows:excludedNonZero.length,organizations:new Set(scoped.map(r=>`${r.bookCode}|${r.orgCode}|${r.orgName}`)).size,sourceAccounts:new Set(scoped.map(r=>r.accountCode)).size,outputRows:rows.length},errors,warnings,conservation:{sourceCents,allocatedCents,differenceCents:allocatedCents-sourceCents,passed:conservationPassed,byCategory:breakdown('category:'),bySourceAccount:breakdown('account:'),bySourceOrganization:breakdown('org:')},reconciliations:rec.results,...(journalVerification?{journalVerification}:{}),systemMetrics:rec.systemMetrics,hashes:{balanceSha256,profitSha256,...(journalSha256?{journalSha256}:{}),...(outputSha256?{outputSha256}:{})}};return{normalized,profits,rows,report,output};
}
