import type { DB } from '../../../db/connection';
import type { ConvertedRow, NormalizedProfitRow, ReconciliationResult, ValidationIssue } from '../finance.types';
import { loadSnapshotNodes } from '../../tree/snapshot';
import { loadMetricDefinitions } from '../mapping/metric-snapshot';

interface Rule {source_line_alias:string;target_type:'account'|'metric';target_code:string;org_scope_json:string;tolerance_cents:number;required:0|1}
function descendants(rows:{id:number;parent_id:number|null;code:string}[],rootCode:string):Set<number>{const root=rows.find(r=>r.code===rootCode);if(!root)return new Set();const out=new Set([root.id]);let changed=true;while(changed){changed=false;for(const r of rows)if(r.parent_id!=null&&out.has(r.parent_id)&&!out.has(r.id)){out.add(r.id);changed=true;}}return out;}
export function reconcile(db:DB,versionId:number,profits:NormalizedProfitRow[],output:ConvertedRow[]):{results:ReconciliationResult[];errors:ValidationIssue[];systemMetrics:Record<string,number>}{
  const rules=db.prepare('SELECT * FROM finance_reconciliation_rule WHERE mapping_version_id=? ORDER BY id').all(versionId) as Rule[];const errors:ValidationIssue[]=[];const version=db.prepare('SELECT account_tree_snapshot_id FROM finance_mapping_version WHERE id=?').get(versionId) as {account_tree_snapshot_id:number}|undefined;if(!version)throw new Error(`映射版本 ${versionId} 不存在`);const accounts=loadSnapshotNodes(db,version.account_tree_snapshot_id) as {id:number;parent_id:number|null;code:string;type:string}[];const {metrics,terms}=loadMetricDefinitions(db,versionId);const metricByCode=new Map(metrics.map(m=>[m.code,m])),metricById=new Map(metrics.map(m=>[m.metric_id,m]));
  const coveredAliases=new Set(rules.map(rule=>rule.source_line_alias.trim()));
  for(const row of profits){if(row.amountCents!==0&&!coveredAliases.has(row.item.trim()))errors.push({gate:'reconciliation',code:'PROFIT_UNCOVERED',message:`官方利润表非零项目“${row.item}”没有勾稽规则`,sourceSheet:row.sourceSheet,sourceRow:row.sourceRow});}
  const accountTotals=new Map<string,number>();for(const r of output)accountTotals.set(r.accountCode,(accountTotals.get(r.accountCode)??0)+r.displayCents);
  const metricCache=new Map<string,number>();const accountValue=(code:string,signed:boolean,orgScope:Set<string>)=>{const ids=descendants(accounts,code);return output.filter(r=>ids.has(r.accountId)&&(!orgScope.size||orgScope.has(r.orgCode))).reduce((s,r)=>s+r.displayCents*(signed&&r.accountType!=='income'?-1:1),0);};
  const metricValue=(code:string,orgScope:Set<string>,stack=new Set<string>()):number=>{const key=`${code}|${[...orgScope].sort().join(',')}`;if(metricCache.has(key))return metricCache.get(key)!;if(stack.has(code))throw new Error(`指标循环:${code}`);stack.add(code);const metric=metricByCode.get(code);if(!metric)return 0;const metricTerms=terms.filter(t=>t.metric_id===metric.metric_id);let total=0;for(const t of metricTerms){if(t.source_type==='account'){const acc=accounts.find(a=>a.id===t.source_account_id);if(acc)total+=accountValue(acc.code,true,orgScope)*t.coefficient;}else{const m=t.source_metric_id==null?undefined:metricById.get(t.source_metric_id);if(m)total+=metricValue(m.code,orgScope,new Set(stack))*t.coefficient;}}metricCache.set(key,total);return total;};
  const results:ReconciliationResult[]=[];for(const rule of rules){const matches=profits.filter(p=>p.item.trim()===rule.source_line_alias.trim());if(matches.length!==1){if(rule.required){errors.push({gate:'reconciliation',code:matches.length?'PROFIT_DUPLICATE':'PROFIT_MISSING',message:`官方利润表项目“${rule.source_line_alias}”${matches.length?'重复':'缺失'}`});}else{results.push({item:rule.source_line_alias,targetType:rule.target_type,targetCode:rule.target_code,officialCents:matches[0]?.amountCents??0,mappedCents:0,differenceCents:0,toleranceCents:rule.tolerance_cents,passed:true,skipped:matches.length?'duplicate':'missing'});}continue;}const scope=new Set(JSON.parse(rule.org_scope_json||'[]') as string[]);const mapped=rule.target_type==='account'?accountValue(rule.target_code,false,scope):metricValue(rule.target_code,scope);const official=matches[0].amountCents,difference=mapped-official,passed=Math.abs(difference)<=rule.tolerance_cents;results.push({item:rule.source_line_alias,targetType:rule.target_type,targetCode:rule.target_code,officialCents:official,mappedCents:mapped,differenceCents:difference,toleranceCents:rule.tolerance_cents,passed});if(!passed)errors.push({gate:'reconciliation',code:'PROFIT_MISMATCH',message:`${rule.source_line_alias} 勾稽差异 ${difference} 分，允许 ${rule.tolerance_cents} 分`,sourceSheet:matches[0].sourceSheet,sourceRow:matches[0].sourceRow});}
  if(!rules.length)errors.push({gate:'reconciliation',code:'NO_RECONCILIATION_RULES',message:'映射版本没有利润表勾稽规则'});const systemMetrics=Object.fromEntries(['P01','P02','P03','P04','P05','P06','P07'].filter(code=>metricByCode.has(code)).map(code=>[code,metricValue(code,new Set())]));return {results,errors,systemMetrics};
}
