import fs from 'fs';
import path from 'path';
import ExcelJS from 'exceljs';
import { args,database,required } from './finance-cli';
import { getSourceProfileByCode } from '../src/modules/finance-import/source-profile.service';
import { adapterFor } from '../src/modules/finance-import/parser/fixed-finance-system';
import { isAccountVisibleForScope } from '../src/core/accountScope';

interface Candidate{sourceType:'org'|'account';sourceKey:string;candidates:{targetCode:string;reason:string;confidence:number;ambiguity:string;requiresSplit:boolean}[]}
const PROMPT_VERSION='finance-mapping-v1';
async function main(){const a=args(),apiKey=process.env.OPENAI_API_KEY;if(!apiKey)throw new Error('缺少 OPENAI_API_KEY；AI 候选是可选审核辅助，月度正式转换不依赖此变量');const db=database(a),profile=getSourceProfileByCode(db,required(a,'profile')),year=Number(required(a,'year')),snapshotDate=required(a,'snapshot-date');const rows=await adapterFor(profile.adapter_type).parseBalance(fs.readFileSync(required(a,'balance')),{year,snapshotDate,config:JSON.parse(profile.config_json)});
  // 明确去金额化：发给模型的对象不含借方、贷方或任何金额字段。
  const allSources=[...new Map(rows.flatMap(r=>[{sourceType:'org' as const,sourceKey:`${r.bookCode}|${r.orgCode}|${r.orgName}`,name:r.orgName,auxiliary:r.auxiliary},{sourceType:'account' as const,sourceKey:`${r.accountCode}|${r.accountName}`,name:r.accountName,auxiliary:r.auxiliary}]).map(x=>[`${x.sourceType}:${x.sourceKey}`,x])).values()];
  const mappingVersionId=a['mapping-version']?Number(a['mapping-version']):undefined,knownOrg=mappingVersionId?new Set((db.prepare('SELECT source_book_code,source_org_code,source_org_name FROM finance_org_mapping WHERE mapping_version_id=?').all(mappingVersionId) as any[]).map(r=>`${r.source_book_code}|${r.source_org_code}|${r.source_org_name}`)):new Set<string>(),knownAccount=mappingVersionId?new Set((db.prepare('SELECT source_account_code,source_account_name FROM finance_account_mapping WHERE mapping_version_id=?').all(mappingVersionId) as any[]).map(r=>`${r.source_account_code}|${r.source_account_name}`)):new Set<string>();const sources=allSources.filter(s=>s.sourceType==='org'?!knownOrg.has(s.sourceKey):!knownAccount.has(s.sourceKey));
  const orgRows=db.prepare("SELECT id,parent_id,code,name FROM org WHERE status='active' ORDER BY code").all() as {id:number;parent_id:number|null;code:string;name:string}[],orgParents=new Set(orgRows.map(r=>r.parent_id).filter((x):x is number=>x!=null)),leafOrgCodes=orgRows.filter(r=>!orgParents.has(r.id)).map(r=>r.code),orgTargets=orgRows.map(({code,name})=>({code,name}));const accountTargets=(db.prepare("SELECT code,name,type FROM account WHERE status='active' ORDER BY code").all() as {code:string;name:string;type:string}[]).map(account=>({...account,applicableLeafOrgCodes:leafOrgCodes.filter(orgCode=>isAccountVisibleForScope(account.code,new Set([orgCode])))}));const targetCodes=new Set([...orgTargets.map(x=>x.code),...accountTargets.map(x=>x.code)]);const docsDir=path.resolve(process.cwd(),'../docs'),referenceDocuments=['澧水预算科目编码.md','澧水预算组织编码.md'].map(name=>({name,content:fs.existsSync(path.join(docsDir,name))?fs.readFileSync(path.join(docsDir,name),'utf8').slice(0,50000):''}));
  const schema={type:'object',properties:{items:{type:'array',items:{type:'object',properties:{sourceType:{type:'string',enum:['org','account']},sourceKey:{type:'string'},candidates:{type:'array',maxItems:3,items:{type:'object',properties:{targetCode:{type:'string'},reason:{type:'string'},confidence:{type:'number',minimum:0,maximum:1},ambiguity:{type:'string'},requiresSplit:{type:'boolean'}},required:['targetCode','reason','confidence','ambiguity','requiresSplit'],additionalProperties:false}}},required:['sourceType','sourceKey','candidates'],additionalProperties:false}}},required:['items'],additionalProperties:false};const model=process.env.OPENAI_MODEL??'gpt-5-mini';const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${apiKey}`,'content-type':'application/json'},body:JSON.stringify({model,input:[{role:'system',content:'你只生成财务组织/科目到预算树的候选映射审核建议。不得虚构目标编码，不处理金额，不执行拆分或正式转换。'},{role:'user',content:JSON.stringify({sources,orgTargets,accountTargets,referenceDocuments})}],text:{format:{type:'json_schema',name:'finance_mapping_candidates',strict:true,schema}}})});if(!response.ok)throw new Error(`OpenAI Responses API ${response.status}: ${await response.text()}`);const body=await response.json() as any;const text=body.output?.flatMap((o:any)=>o.content??[]).find((c:any)=>c.type==='output_text')?.text;if(!text)throw new Error('模型未返回结构化候选');const parsed=JSON.parse(text) as {items:Candidate[]};const sourceKeys=new Set(sources.map(s=>`${s.sourceType}:${s.sourceKey}`));for(const item of parsed.items){if(!sourceKeys.has(`${item.sourceType}:${item.sourceKey}`))throw new Error(`AI 返回未知来源:${item.sourceKey}`);if(item.candidates.length>3)throw new Error('AI 每项候选不得超过三个');for(const c of item.candidates)if(!targetCodes.has(c.targetCode))throw new Error(`AI 返回未知目标编码:${c.targetCode}`);}
  const orgTargetCodes=new Set(orgTargets.map(t=>t.code)),accountTargetCodes=new Set(accountTargets.map(t=>t.code));for(const item of parsed.items)for(const candidate of item.candidates)if(!(item.sourceType==='org'?orgTargetCodes:accountTargetCodes).has(candidate.targetCode))throw new Error(`AI 返回目标类型不匹配:${item.sourceType}/${candidate.targetCode}`);
  const wb=new ExcelJS.Workbook(),meta=wb.addWorksheet('AI候选元数据');meta.addRows([['模型',model],['提示词版本',PROMPT_VERSION],['生成时间',new Date().toISOString()],['金额字段',0],['增量来源数',sources.length],['用途','仅供人工审核，不直接写正式映射']]);const sheet=wb.addWorksheet('待审核候选');sheet.addRow(['来源类型','来源标识','候选序号','目标编码','理由','置信度','歧义','需要拆分','审核结论','审核备注']);for(const item of parsed.items)for(let i=0;i<item.candidates.length;i++){const c=item.candidates[i];sheet.addRow([item.sourceType,item.sourceKey,i+1,c.targetCode,c.reason,c.confidence,c.ambiguity,c.requiresSplit?'是':'否','','']);}
  // 下面三张表与页面的草稿导入格式一致；AI 不预填正式目标，必须由人工选择候选并补全规则。
  const orgSheet=wb.addWorksheet('组织映射');orgSheet.addRow(['源账套','源组织编码','源组织名称','辅助条件JSON','目标组织编码','优先级','依据']);for(const source of sources.filter(s=>s.sourceType==='org')){const [bookCode,orgCode,orgName]=source.sourceKey.split('|');orgSheet.addRow([bookCode,orgCode,orgName,JSON.stringify(source.auxiliary),'',0,'']);}
  const accountSheet=wb.addWorksheet('科目映射');accountSheet.addRow(['源科目编码','源科目名称','辅助条件JSON','目标科目编码','金额规则','分配方式','权重','优先级','状态','依据']);for(const source of sources.filter(s=>s.sourceType==='account')){const [accountCode,accountName]=source.sourceKey.split('|');accountSheet.addRow([accountCode,accountName,JSON.stringify(source.auxiliary),'','debit_minus_credit','direct',1000000,0,'active','']);}
  const reconciliationSheet=wb.addWorksheet('利润表勾稽');reconciliationSheet.addRow(['官方项目','目标类型','目标编码','组织范围JSON','容差分','容差原因','必填']);
  fs.writeFileSync(required(a,'output'),Buffer.from(await wb.xlsx.writeBuffer()));db.close();}
main().catch(e=>{console.error(e instanceof Error?e.message:e);process.exit(1);});
