import { expect, login, test } from './access';
import type { Page } from '@playwright/test';

async function ask(page: Page, message: string) {
  const before = await page.getByTestId('assistant-dock-answer').count();
  await page.getByTestId('assistant-dock-input').fill(message);
  await page.getByTestId('assistant-dock-send').click();
  await expect(page.getByTestId('assistant-dock-answer')).toHaveCount(before + 1);
  await expect(page.getByTestId('assistant-dock-stop')).toHaveCount(0);
  return page.getByTestId('assistant-dock-answer').last();
}

test('跨域助手：实际合同对象、筛选、页签切换和桌面/移动端呈现', async ({ page, request }, info) => {
  const orgs = await (await request.get('/api/org/tree')).json();
  const orgId = orgs.rows.find((o: any) => o.code === 'SH').id;
  const created = await request.post('/api/contracts', { data: { contractNo: `HT-AI-${Date.now()}`, name: '助手来源核验合同', orgId, originalAmount: '90071992547409.93' } });
  expect(created.ok()).toBeTruthy(); const contract = await created.json();
  await login(page);
  await page.goto(`/contracts?id=${contract.id}`);
  await expect(page.getByRole('dialog').filter({ hasText: '助手来源核验合同' })).toBeVisible();
  await page.getByTestId('assistant-dock-trigger').click();
  const payloads: any[] = [];
  page.on('request', (req) => { if (req.url().includes('/api/assistant/chat')) payloads.push(req.postDataJSON()); });
  const answer = await ask(page, '当前合同金额和付款情况');
  await expect(answer).toContainText('90071992547409.93');
  expect(payloads.at(-1).pageContext.scope.contractId).toBe(contract.id);
  await expect(page.getByTestId('assistant-dock-context-summary').last()).toContainText(`合同 #${contract.id}`);
  await page.screenshot({ path: info.outputPath('assistant-contract-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByTestId('assistant-dock-input')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath('assistant-contract-mobile.png'), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  const excluded = await request.post('/api/contracts', { data: { contractNo: `HT-OUT-${Date.now()}`, name: '筛选外合同', orgId, originalAmount: '12.34' } });
  expect(excluded.ok()).toBeTruthy();
  await page.goto('/contracts?status=active&keyword=助手来源核验合同');
  if (!(await page.getByTestId('assistant-dock-input').isVisible())) await page.getByTestId('assistant-dock-trigger').click();
  const filtered = await ask(page, '当前有哪些合同');
  expect(payloads.at(-1).pageContext.view).toMatchObject({ status: 'active', keyword: '助手来源核验合同' });
  expect(payloads.at(-1).pageContext.scope.contractId).toBeUndefined();
  await expect(filtered).toContainText('助手来源核验合同');
  await expect(filtered).not.toContainText('筛选外合同');
  await page.goto(`/eas?orgId=${orgId}&period=2026-05`);
  await page.getByRole('tab', { name: '期间锁', exact: true }).click();
  if (!(await page.getByTestId('assistant-dock-input').isVisible())) await page.getByTestId('assistant-dock-trigger').click();
  await ask(page, '当前有哪些记录');
  expect(payloads.at(-1).pageContext.view.tab).toBe('locks');
  expect(payloads.at(-1).pageContext.scope.contractId).toBeUndefined();
  await page.getByRole('tab', { name: '期间工作台' }).click();
  await ask(page, '当前 EAS 对账状态');
  expect(payloads.at(-1).pageContext.scope.period).toBe('2026-05');
  expect(payloads.at(-1).pageContext.view.tab).not.toBe('locks');
  await page.goto('/assistant');
  await expect(page.getByRole('combobox', { name: '提问业务范围' })).toBeVisible();
  await page.screenshot({ path: info.outputPath('assistant-home-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('combobox', { name: '提问业务范围' })).toBeVisible();
  expect(await page.getByRole('combobox', { name: '提问业务范围' }).evaluate((el) => { const r = el.getBoundingClientRect(); return r.height > 0 && r.top < window.innerHeight; })).toBe(true);
  expect(await page.locator('.newfc-ai-recommend-two').evaluate((el) => getComputedStyle(el).gridTemplateColumns.trim().split(/\s+/).length)).toBe(1);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath('assistant-home-mobile.png'), fullPage: true });
  const composer = page.getByPlaceholder('例如：当前合同金额与已付款是多少？财报的净利润和来源是什么？');
  await composer.scrollIntoViewIfNeeded();
  await expect(composer).toBeVisible();
  expect(await composer.evaluate((el) => { const r = el.getBoundingClientRect(); return r.top >= 0 && r.bottom <= window.innerHeight; })).toBe(true);
  await composer.fill('当前有哪些高风险与逾期整改');
  await composer.scrollIntoViewIfNeeded();
  await expect.poll(() => composer.evaluate((el) => { const r = el.getBoundingClientRect(); return r.top >= 0 && r.bottom <= window.innerHeight; })).toBe(true);
  await page.screenshot({ path: info.outputPath('assistant-home-mobile-composer.png'), fullPage: true });
});
