import { Errors } from '../../../core/errors';
import type { NormalizedFinanceRow } from '../finance.types';

export interface OrgMapping { id:number; source_book_code:string; source_org_code:string; source_org_name:string; source_aux_json:string; target_org_id:number; priority:number }
export interface AccountMapping { id:number; source_account_code:string; source_account_name:string; source_aux_json:string; target_account_id:number; amount_rule:'credit'|'debit'|'credit_minus_debit'|'debit_minus_credit'; allocation_method:'direct'|'fixed_ratio'; allocation_weight:number; priority:number; status:string }

function auxMatches(raw:string, actual:Record<string,string>):boolean { const expected=JSON.parse(raw||'{}') as Record<string,string>; return Object.entries(expected).every(([k,v])=>actual[k]===String(v)); }
function choose<T extends {priority:number}>(matches:T[],label:string,row:NormalizedFinanceRow):T[] { if(!matches.length) throw Errors.validation(`${row.sourceSheet}!${row.sourceRow} ${label}未映射`); const top=Math.max(...matches.map(m=>m.priority)); const selected=matches.filter(m=>m.priority===top); return selected; }
export function matchOrg(row:NormalizedFinanceRow,rules:OrgMapping[]):OrgMapping { const candidates=rules.filter(r=>(!r.source_book_code||r.source_book_code===row.bookCode)&&(!r.source_org_code||r.source_org_code===row.orgCode)&&(!r.source_org_name||r.source_org_name===row.orgName)&&auxMatches(r.source_aux_json,row.auxiliary)); const selected=choose(candidates,'组织',row); if(selected.length!==1) throw Errors.validation(`${row.sourceSheet}!${row.sourceRow} 组织映射同优先级多重命中`); return selected[0]; }
export function matchAccounts(row:NormalizedFinanceRow,rules:AccountMapping[]):AccountMapping[] { const candidates=rules.filter(r=>r.status==='active'&&r.source_account_code===row.accountCode&&(!r.source_account_name||r.source_account_name===row.accountName)&&auxMatches(r.source_aux_json,row.auxiliary)); const selected=choose(candidates,'科目',row); const conditionKeys=new Set(selected.map(r=>`${r.source_account_name}|${r.source_aux_json}`));if(conditionKeys.size!==1)throw Errors.validation(`${row.sourceSheet}!${row.sourceRow} 科目映射同优先级多重条件命中`);const group=selected.filter(r=>r.amount_rule===selected[0].amount_rule&&r.allocation_method===selected[0].allocation_method); if(group.length!==selected.length) throw Errors.validation(`${row.sourceSheet}!${row.sourceRow} 科目映射同优先级规则组冲突`); if(group.length>1&&group[0].allocation_method!=='fixed_ratio') throw Errors.validation(`${row.sourceSheet}!${row.sourceRow} 直接映射不允许一对多`); return group; }
export function amountFor(row:NormalizedFinanceRow,rule:AccountMapping['amount_rule']):number { switch(rule){case'credit':return row.cumulativeCreditCents;case'debit':return row.cumulativeDebitCents;case'credit_minus_debit':return row.cumulativeCreditCents-row.cumulativeDebitCents;case'debit_minus_credit':return row.cumulativeDebitCents-row.cumulativeCreditCents;} }
