import type { Permission } from './permissions';

/** The shared page contract is pure data; components and menu ordering stay in the browser. */
export type DomainCapability = 'overview' | 'assistant_content' | 'master_data' | 'budget' | 'actual' | 'execution' | 'comparison' | 'import_conversion' | 'evidence' | 'operations' | 'finance_data' | 'project_data' | 'risk_investment' | 'domain_support';
export type DraftKind = 'budget_grid' | 'actual_grid' | 'org_form' | 'account_form' | 'metric_formula' | 'calculation_rule' | 'cleaning_template' | 'alias_rule';
export type AssistantEntityType = string;
export interface PageDefinition {
  path: string;
  menuHost?: 'budget_versions' | 'master_entities' | 'backup';
  entryPath: string;
  tab?: string;
  label: string;
  menuLabel: string;
  permission: Permission;
  allOrgs: boolean;
  viewFields: string[];
  entityTypes: AssistantEntityType[];
  factTypes: string[];
  focusKinds: string[];
  selectionModes: ('bounds' | 'refs' | 'query')[];
  draftKinds: DraftKind[];
  defaultCapability: DomainCapability;
  capabilities: DomainCapability[];
}
export const PAGE_CATALOG = {
  eas: {"path": "/eas", "entryPath": "/eas", "label": "EAS 工作区", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "EAS 工作区", "permission": "eas:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  governance: {"path": "/governance", "entryPath": "/governance", "label": "数据治理", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "数据治理", "permission": "governance:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  statements: {"path": "/statements", "entryPath": "/statements", "label": "财务报表", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "财务报表", "permission": "statements:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  mgmt: {"path": "/mgmt", "entryPath": "/mgmt", "label": "管理会计", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "管理会计", "permission": "mgmt:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  standard_reports: {"path": "/standard-reports", "entryPath": "/standard-reports", "label": "标准报表", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "标准报表", "permission": "report:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  project_budget: {"path": "/project-budget", "entryPath": "/project-budget", "label": "项目预算", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "项目预算", "permission": "project_budget:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  plan: {"path": "/plan", "entryPath": "/plan", "label": "计划执行", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "计划执行", "permission": "plan:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  contracts: {"path": "/contracts", "entryPath": "/contracts", "label": "合同台账", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "合同台账", "permission": "contract:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  contract_import: {"path": "/contracts/import", "entryPath": "/contracts/import", "label": "合同导入", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "合同导入", "permission": "contract:import", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  expense: {"path": "/expense", "entryPath": "/expense", "label": "费用审核", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "报销单", "permission": "expense:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  expense_policies: {"path": "/expense/policies", "entryPath": "/expense/policies", "label": "制度依据", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "制度依据", "permission": "expense:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  feasibility: {"path": "/feasibility", "entryPath": "/feasibility", "label": "可行性测算", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "可行性测算", "permission": "investment:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  investment_control: {"path": "/investment-control", "entryPath": "/investment-control", "label": "投资控制", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "投资控制", "permission": "investment:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  forecast: {"path": "/forecast", "entryPath": "/forecast", "label": "财务预测", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "财务预测", "permission": "forecast:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  risk: {"path": "/risk", "entryPath": "/risk", "label": "风险台账", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "风险台账", "permission": "risk:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  analysis_reports: {"path": "/analysis-reports", "entryPath": "/analysis-reports", "label": "分析报告", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "分析报告", "permission": "report:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  master_entities: {"path": "/master-entities", "entryPath": "/master-entities", "label": "主数据", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "项目·供应商·映射", "permission": "master:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  project_profile: {"menuHost": "master_entities", "path": "/projects/:id", "entryPath": "/master-entities?tab=projects", "label": "项目全景", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "项目全景", "permission": "master:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  search: {"path": "/search", "entryPath": "/search", "label": "跨域检索", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "跨域检索", "permission": "search:use", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  jobs: {"path": "/jobs", "entryPath": "/jobs", "label": "任务中心", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "任务中心", "permission": "tasks:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  business_settings: {"path": "/settings/business", "entryPath": "/settings/business", "label": "业务设置", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "业务设置", "permission": "settings:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  security: {"path": "/settings/security", "entryPath": "/settings/security", "label": "授权管理", "viewFields": ["tab", "status", "keyword", "sourceType", "kind", "level", "reportType", "includeRetired", "expenseType"], "entityTypes": ["row", "card", "statement_batch", "project_budget_batch", "plan_batch", "eas_batch", "feasibility_report", "job", "project", "contract", "expense_claim", "feasibility_project", "feasibility_scenario", "investment_project", "investment_comparison", "forecast_model", "forecast_version", "forecast_run", "risk_event", "analysis_report", "standard_report", "governance_issue", "mgmt_metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "domain_support", "capabilities": ["finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "用户与权限", "permission": "security:manage", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  dashboard: {"path": "/", "entryPath": "/", "label": "首页工作台", "viewFields": ["dashboardSubject"], "entityTypes": ["row", "tree_node", "card", "org", "account", "metric", "anomaly", "budget_version", "actual_snapshot"], "factTypes": ["verification"], "draftKinds": [], "defaultCapability": "overview", "capabilities": ["overview", "execution", "evidence", "finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "首页", "permission": "dashboard:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  assistant: {"path": "/assistant", "entryPath": "/assistant", "label": "财务助手", "viewFields": [], "entityTypes": ["insight", "report_section", "card"], "factTypes": [], "draftKinds": [], "defaultCapability": "assistant_content", "capabilities": ["assistant_content", "execution", "comparison", "budget", "actual", "master_data", "import_conversion", "operations", "overview", "evidence", "finance_data", "project_data", "risk_investment", "domain_support"], "menuLabel": "对话", "permission": "assistant:use", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  insights: {"path": "/insights", "entryPath": "/insights", "label": "洞察报告", "viewFields": ["kind", "status"], "entityTypes": ["insight", "report_section", "card"], "factTypes": [], "draftKinds": [], "defaultCapability": "assistant_content", "capabilities": ["assistant_content"], "menuLabel": "洞察报告", "permission": "assistant:use", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  master_health: {"path": "/master-health", "entryPath": "/master-health", "label": "主数据健康", "viewFields": ["dimension", "issueType", "status", "search"], "entityTypes": ["row", "tree_node", "card", "org", "account", "metric"], "factTypes": [], "draftKinds": [], "defaultCapability": "master_data", "capabilities": ["master_data"], "menuLabel": "健康体检", "permission": "master:read", "allOrgs": true, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  cleaning_config: {"path": "/cleaning-config", "entryPath": "/cleaning-config", "label": "清洗配置", "viewFields": ["tab", "targetKind", "status", "search"], "entityTypes": ["row", "cleaning_template", "alias_rule"], "factTypes": [], "draftKinds": ["cleaning_template", "alias_rule"], "defaultCapability": "import_conversion", "capabilities": ["import_conversion"], "menuLabel": "清洗模板与别名", "permission": "import:run", "allOrgs": true, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": ["refs", "query"]},
  budget_progress: {"path": "/progress", "entryPath": "/progress", "label": "编制进度", "viewFields": ["status"], "entityTypes": ["card", "row", "progress_row", "org"], "factTypes": [], "draftKinds": [], "defaultCapability": "budget", "capabilities": ["budget", "overview", "execution"], "menuLabel": "进度总览", "permission": "budget:read", "allOrgs": true, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  anomaly_center: {"path": "/alerts", "entryPath": "/alerts", "label": "异常预警中心", "viewFields": ["anomalyType", "severity", "status", "threshold", "yoyThreshold", "peerThreshold"], "entityTypes": ["anomaly", "row", "org", "account"], "factTypes": [], "draftKinds": [], "defaultCapability": "execution", "capabilities": ["overview", "execution"], "menuLabel": "预警中心", "permission": "analysis:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  metric_trend: {"path": "/metric-trend", "entryPath": "/metric-trend", "label": "指标趋势", "viewFields": ["series", "versionIds"], "entityTypes": ["metric", "card"], "factTypes": [], "draftKinds": [], "defaultCapability": "comparison", "capabilities": ["comparison", "evidence"], "menuLabel": "指标趋势", "permission": "analysis:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  ai_settings: {"path": "/settings/ai", "entryPath": "/settings/ai", "label": "AI 渠道设置", "viewFields": ["tab", "testStatus"], "entityTypes": ["ai_channel", "feature_binding", "row"], "factTypes": [], "draftKinds": [], "defaultCapability": "operations", "capabilities": ["operations"], "menuLabel": "AI 渠道设置", "permission": "settings:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  org: {"path": "/org", "entryPath": "/org", "label": "组织管理", "viewFields": ["status", "search"], "entityTypes": ["tree_node", "row", "org"], "factTypes": [], "draftKinds": ["org_form"], "defaultCapability": "master_data", "capabilities": ["master_data"], "menuLabel": "组织", "permission": "master:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  account: {"path": "/account", "entryPath": "/account", "label": "科目管理", "viewFields": ["type", "sheetKey", "scopeKey", "search"], "entityTypes": ["tree_node", "row", "account"], "factTypes": [], "draftKinds": ["account_form"], "defaultCapability": "master_data", "capabilities": ["master_data"], "menuLabel": "科目", "permission": "master:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  metric: {"path": "/metric", "entryPath": "/metric", "label": "报表指标", "viewFields": ["category", "status"], "entityTypes": ["row", "metric"], "factTypes": [], "draftKinds": ["metric_formula"], "defaultCapability": "master_data", "capabilities": ["master_data"], "menuLabel": "指标", "permission": "master:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": ["refs", "query"]},
  budget_versions: {"path": "/budget", "entryPath": "/budget", "label": "预算与预测版本", "viewFields": ["kind", "status", "sort"], "entityTypes": ["row", "budget_version"], "factTypes": [], "draftKinds": [], "defaultCapability": "budget", "capabilities": ["budget"], "menuLabel": "预算与预测", "permission": "budget:read", "allOrgs": true, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  budget_edit: {"menuHost": "budget_versions", "path": "/budget/:id", "entryPath": "/budget", "label": "预算编制表格", "viewFields": ["sheetKey", "orgView", "accountView", "keyword", "nonZeroOnly", "collapseLevel"], "entityTypes": ["row", "tree_node", "org", "account", "budget_version", "check_item"], "factTypes": ["verification"], "draftKinds": ["budget_grid"], "defaultCapability": "budget", "capabilities": ["budget", "evidence"], "menuLabel": "预算编制表格", "permission": "budget:read", "allOrgs": true, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": ["bounds"]},
  actual: {"path": "/actual", "entryPath": "/actual", "label": "实际录入与快照", "viewFields": ["sheetKey", "viewMode", "historyMode", "keyword", "nonZeroOnly", "collapseLevel", "cutoff"], "entityTypes": ["row", "tree_node", "org", "account", "actual_snapshot"], "factTypes": [], "draftKinds": ["actual_grid"], "defaultCapability": "actual", "capabilities": ["actual", "evidence"], "menuLabel": "实际录入与快照", "permission": "actual:read", "allOrgs": true, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": ["bounds"]},
  finance_import: {"path": "/finance", "entryPath": "/finance", "label": "财务系统转换", "viewFields": ["step", "status"], "entityTypes": ["row", "conversion", "mapping_version", "verification_gate"], "factTypes": [], "draftKinds": [], "defaultCapability": "import_conversion", "capabilities": ["import_conversion"], "menuLabel": "财务系统转换", "permission": "finance_import:manage", "allOrgs": true, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  analysis: {"path": "/analysis", "entryPath": "/analysis", "label": "年度执行分析", "viewFields": ["sheetKey", "summaryLevel", "threshold", "trend", "accountSearch"], "entityTypes": ["row", "org", "account", "metric", "card"], "factTypes": ["verification"], "draftKinds": [], "defaultCapability": "execution", "capabilities": ["execution", "evidence"], "menuLabel": "年度执行分析", "permission": "analysis:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  structure: {"path": "/structure", "entryPath": "/structure", "label": "结构分析", "viewFields": ["sheetKey", "summaryLevel", "basisMode", "basisId", "accountSearch"], "entityTypes": ["row", "tree_node", "org", "account", "metric"], "factTypes": ["verification"], "draftKinds": [], "defaultCapability": "comparison", "capabilities": ["comparison", "evidence"], "menuLabel": "结构占比", "permission": "analysis:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  history: {"path": "/history", "entryPath": "/history", "label": "历年对比与趋势", "viewFields": ["versionRule", "dimension"], "entityTypes": ["row", "metric", "account", "org"], "factTypes": [], "draftKinds": [], "defaultCapability": "comparison", "capabilities": ["comparison"], "menuLabel": "历年对比", "permission": "analysis:read", "allOrgs": true, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  version_compare: {"path": "/compare", "entryPath": "/compare", "label": "版本对比", "viewFields": ["direction", "sort", "sheetKey"], "entityTypes": ["row", "org", "account", "metric", "budget_version"], "factTypes": ["verification"], "draftKinds": [], "defaultCapability": "comparison", "capabilities": ["comparison", "evidence"], "menuLabel": "版本对比", "permission": "analysis:read", "allOrgs": true, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  calculations: {"menuHost": "budget_versions", "path": "/data", "entryPath": "/data?tab=calculations", "tab": "calculations", "label": "测算模板", "viewFields": ["ruleType", "status", "search"], "entityTypes": ["row", "calculation_rule"], "factTypes": [], "draftKinds": ["calculation_rule"], "defaultCapability": "budget", "capabilities": ["budget"], "menuLabel": "测算模板", "permission": "budget:read", "allOrgs": true, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  imports: {"path": "/data", "entryPath": "/data?tab=imports", "tab": "imports", "label": "导入批次", "viewFields": ["importType", "status", "dateFrom", "dateTo"], "entityTypes": ["row", "import_batch"], "factTypes": [], "draftKinds": [], "defaultCapability": "import_conversion", "capabilities": ["import_conversion"], "menuLabel": "导入批次", "permission": "import:run", "allOrgs": true, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  data_check: {"path": "/data", "entryPath": "/data?tab=check", "tab": "check", "label": "一致性检查", "viewFields": ["severity", "result"], "entityTypes": ["card", "row", "check_item"], "factTypes": [], "draftKinds": [], "defaultCapability": "operations", "capabilities": ["operations"], "menuLabel": "一致性检查", "permission": "master:read", "allOrgs": true, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  yearclose: {"path": "/data", "entryPath": "/data?tab=yearclose", "tab": "yearclose", "label": "年度关闭", "viewFields": ["status"], "entityTypes": ["row", "yearclose_item", "check_item"], "factTypes": [], "draftKinds": [], "defaultCapability": "operations", "capabilities": ["operations"], "menuLabel": "年度关闭", "permission": "actual:finalize", "allOrgs": true, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  backup: {"path": "/data", "entryPath": "/data?tab=backup", "tab": "backup", "label": "备份与迁移", "viewFields": ["backupType", "status"], "entityTypes": ["row", "backup"], "factTypes": [], "draftKinds": [], "defaultCapability": "operations", "capabilities": ["operations"], "menuLabel": "备份与迁移", "permission": "system:backup", "allOrgs": true, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  migration: {"menuHost": "backup", "path": "/data", "entryPath": "/data?tab=migration", "tab": "migration", "label": "迁移管理", "viewFields": ["direction", "status", "table"], "entityTypes": ["row", "migration_task"], "factTypes": [], "draftKinds": [], "defaultCapability": "operations", "capabilities": ["operations"], "menuLabel": "迁移管理", "permission": "system:backup", "allOrgs": true, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  data_export: {"menuHost": "backup", "path": "/data", "entryPath": "/data?tab=export", "tab": "export", "label": "数据导出", "viewFields": ["exportType"], "entityTypes": ["row", "export_task"], "factTypes": [], "draftKinds": [], "defaultCapability": "operations", "capabilities": ["operations"], "menuLabel": "数据导出", "permission": "analysis:export", "allOrgs": true, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
  logs: {"path": "/data", "entryPath": "/data?tab=logs", "tab": "logs", "label": "操作日志", "viewFields": ["action", "entityType", "user", "result", "dateFrom", "dateTo"], "entityTypes": ["row", "log_entry"], "factTypes": [], "draftKinds": [], "defaultCapability": "operations", "capabilities": ["operations"], "menuLabel": "操作日志", "permission": "audit:read", "allOrgs": false, "focusKinds": ["entity", "cell", "chart_point", "fact", "form_field"], "selectionModes": []},
} satisfies Record<string, PageDefinition>;
export type PageId = keyof typeof PAGE_CATALOG;
export const PAGE_IDS = Object.keys(PAGE_CATALOG) as PageId[];
export function isPageId(value: string): value is PageId {
  return Object.prototype.hasOwnProperty.call(PAGE_CATALOG, value);
}
export function pageDefinition(value: string): PageDefinition | null {
  return isPageId(value) ? PAGE_CATALOG[value] : null;
}
export function pagePath(id: PageId, params: Record<string, string | number> = {}): string {
  const page: PageDefinition = PAGE_CATALOG[id];
  let path = page.path;
  const query = new URLSearchParams(page.path.includes(':id') ? '' : page.entryPath.split('?')[1] ?? '');
  for (const [key, value] of Object.entries(params)) {
    if (key === 'id' && page.path.includes(':id')) {
      if (!/^[1-9]\d*$/.test(String(value))) throw new Error('页面对象 ID 必须是正整数');
      path = path.replace(':id', String(value));
    } else query.set(key, String(value));
  }
  if (path.includes(':id')) return page.entryPath;
  return query.size ? `${path}?${query.toString()}` : path;
}
/** Exact paths and numeric dynamic IDs; query tabs are matched explicitly. */
export function matchPage(pathname: string, search = ''): PageId | null {
  const tab = new URLSearchParams(search).get('tab');
  for (const id of PAGE_IDS) {
    const page: PageDefinition = PAGE_CATALOG[id];
    if (page.tab) { if (pathname === page.path && tab === page.tab) return id; continue; }
    if (page.path === pathname) return id;
    if (page.path.includes(':id') && new RegExp('^' + page.path.replace(':id', '[1-9]\\d*') + '$').test(pathname)) return id;
  }
  return pathname === '/data' ? 'backup' : null;
}
export function pageVisible(id: PageId, has: (permission: Permission) => boolean, allOrgs = true): boolean {
  const page: PageDefinition = PAGE_CATALOG[id];
  return has(page.permission) && (!page.allOrgs || allOrgs);
}
